# Generated by Django 4.0.3 on 2022-04-18 17:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('hood_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/')),
            ],
        ),
    ]
