# Generated by Django 4.0.3 on 2022-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, default='#', max_length=60),
        ),
    ]
