# Generated by Django 4.0.3 on 2022-04-18 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0004_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='images/'),
            preserve_default=False,
        ),
    ]
