# Generated by Django 4.0.3 on 2022-04-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0005_business_business_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
