# Generated by Django 4.0.3 on 2022-04-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0009_rename_name_hood_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='estate',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
